// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIm7i8zQkt--Z0taujrhDp8sGqyy_XGdI',
    appId: '1:496414172863:web:a1b24e9a36708113ff080a',
    messagingSenderId: '496414172863',
    projectId: 'ourtwitter-f7bc6',
    authDomain: 'ourtwitter-f7bc6.firebaseapp.com',
    databaseURL: 'https://ourtwitter-f7bc6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ourtwitter-f7bc6.firebasestorage.app',
    measurementId: 'G-FCWT4QT2PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFok_fDuzWqh-545F6EI9kkesQSK4JTG4',
    appId: '1:496414172863:android:d87fcf1a9a57fb03ff080a',
    messagingSenderId: '496414172863',
    projectId: 'ourtwitter-f7bc6',
    databaseURL: 'https://ourtwitter-f7bc6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ourtwitter-f7bc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2EWXxq1jopXp-mSCrw8DXNzXL8ELxYFM',
    appId: '1:496414172863:ios:38a0aac0e8ea789cff080a',
    messagingSenderId: '496414172863',
    projectId: 'ourtwitter-f7bc6',
    databaseURL: 'https://ourtwitter-f7bc6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ourtwitter-f7bc6.firebasestorage.app',
    iosBundleId: 'com.example.ourtwitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2EWXxq1jopXp-mSCrw8DXNzXL8ELxYFM',
    appId: '1:496414172863:ios:38a0aac0e8ea789cff080a',
    messagingSenderId: '496414172863',
    projectId: 'ourtwitter-f7bc6',
    databaseURL: 'https://ourtwitter-f7bc6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ourtwitter-f7bc6.firebasestorage.app',
    iosBundleId: 'com.example.ourtwitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIm7i8zQkt--Z0taujrhDp8sGqyy_XGdI',
    appId: '1:496414172863:web:aaf3bcb6db41f389ff080a',
    messagingSenderId: '496414172863',
    projectId: 'ourtwitter-f7bc6',
    authDomain: 'ourtwitter-f7bc6.firebaseapp.com',
    databaseURL: 'https://ourtwitter-f7bc6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ourtwitter-f7bc6.firebasestorage.app',
    measurementId: 'G-NDE8BFC2G3',
  );
}
